### ISSUE TITLE
java.lang.NumberFormatException: For input string: "1,99"

### ISSUE THREAD

**Issue by johi2** [smowu/Coffee-Bean-Management-System#1]
Hey , love the project but it keeps giving me this error code:
```
java.lang.NumberFormatException: For input string: "1,99"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:543)
	at FileHandler.readItemFiles(FileHandler.java:35)
	at FileHandler.getAllItems(FileHandler.java:82)
	at Sales.setBestCoffee(Sales.java:25)
	at Sales.<init>(Sales.java:15)
	at FileHandler.readSalesFiles(FileHandler.java:201)
	at Sales.storeSales(Sales.java:136)
	at Sales.storeAllSalesData(Sales.java:104)
	at Order.createOrder(Order.java:165)
	at Cashier.dispEmployeeMenu(Cashier.java:58)
	at Main.main(Main.java:19)
```
Any solutions?

**Comment by smowu** [comment]
It'll only accepts decimal separator with periods from the .txt file, not commas.
